/*
	'mdsseq.inc' generator.
	Usage: gcc tools/gendef.c & a > mdsseq.inc
*/
#include <stdio.h>
#include "seqdef.h"

int main()
{
	printf(";========================================================================\n");
	printf("; MDSDRV sequence format defines\n");
	printf("; This file is autogenerated by 'gendef.c'\n");
	printf(";========================================================================\n");
	printf("\tlist -\n");
	printf("\tif def(MML)&(~def(MMLDEF))\n");
	printf("MMLDEF equ $0002\n");
	printf(";========================================================================\n");
	printf("; note duration parameters (00-7f)\n");
	printf(";========================================================================\n");
	long i;
	long interval = 96;
	for(i=1;i<64;i<<=1)
	{
		printf("l%d equ $%02X\n",i, interval-1);
		printf("t%d equ $%02X\n",i, interval);
		if(interval < 96 && (~interval & 1))
		{
			printf("l%dd equ $%02X\n",i, (interval + (interval>>1) - 1));
			printf("t%dd equ $%02X\n",i, interval + (interval>>1));
		}
		interval >>= 1;
	}
	printf(";========================================================================\n");
	printf("; note commands (80-df)\n");
	printf(";========================================================================\n");
	printf("rest equ $%02X\n",rest_cmd);
	printf("tie equ $%02X\n",tie_cmd);
	for(i=0;i<9*17;i++)
	{
		int nn;
		int oct = i/17;
		int note = i%17;
		nn = note_start +  (oct*12)+note_value[note];
		if(nn <= note_end)
			printf("%s%d equ $%02X\n",note_name[note],oct+1,nn);
	}
	printf(";========================================================================\n");
	printf("; channel commands (%02x-%02x)\n",chn_cmd_base(0),chn_cmd_base(chn_cmd_cnt-1));
	printf(";========================================================================\n");
	for(i=0;i<chn_cmd_cnt;i++)
	{
		printf("%s equ $%02X\n",chn_cmd[i].name,chn_cmd_base(i));
	}
	printf(";========================================================================\n");
	printf("; system commands (%02x-%02x)\n",sys_cmd_base(0),sys_cmd_base(sys_cmd_cnt-1));
	printf(";========================================================================\n");
	for(i=0;i<sys_cmd_cnt;i++)
	{
		printf("%s equ $%02X\n",sys_cmd[i].name,sys_cmd_base(i));
	}
	printf("\telse\n", note_start);
	printf(";========================================================================\n");
	printf("; system defines\n");
	printf(";========================================================================\n");
	printf("mds_rest equ $%02X\n", rest_cmd);
	printf("mds_tie equ $%02X\n", tie_cmd);
	printf("mds_note_start equ $%02X\n", note_start);
	printf("mds_chn_cmd_base equ $%02X\n", chn_cmd_base(0));
	printf("mds_sys_cmd_base equ $%02X\n", sys_cmd_base(0));
	printf("\tendif\n", note_start);
	printf("\tlist +\n");
}
